import './style.css';
import React from 'react'

const HomePage = () => {
  return (
    <div className='homepage'>
      <h1>Bem-vindo à MPL home-page!</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a nulla interdum arcu volutpat ultrices eget vel ex. Pellentesque at sem nunc. Cras volutpat sem eu eros luctus porta. Nulla eleifend, tortor at varius fringilla, risus leo scelerisque lectus, vitae finibus lorem ipsum nec nisi. Sed mollis felis nec bibendum auctor. Nulla sit amet urna placerat augue pharetra scelerisque et nec libero. Donec malesuada, ante in fermentum consequat, ex urna posuere est, id bibendum augue eros sed lorem. Fusce molestie ultricies lectus. In facilisis lorem eu quam imperdiet laoreet.</p>
      <p>Aliquam malesuada, elit sit amet finibus tincidunt, tortor felis sagittis ipsum, a varius ipsum dolor sed odio. Maecenas pretium lacinia leo, ut gravida urna ultricies vitae. Cras congue tempus lorem. Morbi vel dignissim nisl. Integer at finibus nisl. Etiam ligula lorem, suscipit id facilisis ut, sodales quis neque. Donec vel posuere metus. Cras sit amet elit a dolor imperdiet fermentum quis quis diam. Duis ut neque ut ex cursus iaculis eu in augue. Aenean finibus diam ac enim semper, ac laoreet mauris egestas. Praesent ac orci tortor. Morbi sed volutpat lorem, eget eleifend lacus. Donec pretium condimentum nunc at mollis.</p>
      <p>Quisque consectetur in turpis quis accumsan. Pellentesque nec magna quis risus auctor pellentesque. Phasellus eu enim suscipit, tempor ligula nec, feugiat erat. Proin elementum non turpis eget porta. Etiam lacinia neque nisl, a blandit tortor dignissim a. Etiam gravida, leo et ornare sagittis, dolor odio euismod justo, at iaculis lectus nunc vitae metus. Suspendisse tempus pulvinar magna eu suscipit. Vivamus varius porttitor velit, in gravida tortor tristique a. Phasellus eleifend urna in erat congue interdum. Cras lacinia nisl sed leo ornare faucibus. Mauris fermentum ex a sapien auctor, non accumsan tellus bibendum. Sed tincidunt odio mi, in eleifend quam consectetur vel. Donec a nunc mauris. Vestibulum porta pulvinar diam, sodales sagittis sapien hendrerit sed.</p>
      <p>Donec facilisis posuere scelerisque. Donec scelerisque, lacus eu dictum gravida, lorem turpis condimentum neque, molestie pharetra elit massa ac justo. Pellentesque consectetur tellus luctus nulla semper, in porttitor arcu vulputate. Donec justo augue, elementum sit amet finibus molestie, tincidunt ut est. Proin ac facilisis massa. Nullam turpis leo, suscipit a augue in, mattis tempor mauris. Donec ut augue facilisis, porta neque nec, consequat nibh. Curabitur sagittis lacus sit amet tempus varius. Aenean vitae turpis quis turpis rhoncus interdum placerat vel dui.</p>
      <p>Integer venenatis facilisis interdum. Vivamus at molestie magna. Nunc sed lacus sed ligula feugiat semper non ac ipsum. Maecenas vitae enim mauris. Nunc leo risus, sodales et mattis nec, dapibus ut velit. Morbi rhoncus luctus sapien, vitae imperdiet erat venenatis a. Aliquam lacus sem, lacinia eu metus quis, suscipit condimentum ante. Nullam ultricies, erat eu lobortis pulvinar, elit nunc tristique ante, sit amet tincidunt velit neque nec ante. Etiam tellus metus, maximus eu ornare vel, accumsan sit amet odio. Nunc sed lacinia odio, nec venenatis eros. Nulla facilisi.</p>
    </div>
  )
}

export default HomePage